INSERT INTO libro (nombre,sinopsis,portada,anio)  values('10-Day Green Smoothie Cleanse','esta es la sinopsis','https://via.placeholder.com/150X200/',2016);
INSERT INTO libro (nombre,sinopsis,portada,anio)  values('11/22/63: A Novel','esta es la sinopsis','https://via.placeholder.com/150X200/',2011);
INSERT INTO libro (nombre,sinopsis,portada,anio)  values('12 Rules for Life: An Antidote to Chaos','esta es la sinopsis','https://via.placeholder.com/150X200/',2018);
INSERT INTO libro (nombre,sinopsis,portada,anio)  values('1984 (Signet Classics)','esta es la sinopsis','https://via.placeholder.com/150X200/',2017);
INSERT INTO libro (nombre,sinopsis,portada,anio)  values('5,000 Awesome Facts (About Everything!) (National Geographic Kids)','esta es la sinopsis','https://via.placeholder.com/150X200/',2019);
INSERT INTO libro (nombre,sinopsis,portada,anio)  values('A Dance with Dragons (A Song of Ice and Fire)','esta es la sinopsis','https://via.placeholder.com/150X200/',2011);
INSERT INTO libro (nombre,sinopsis,portada,anio)  values('A Game of Thrones / A Clash of Kings / A Storm of Swords / A Feast of Crows / A Dance with Dragons','esta es la sinopsis','https://via.placeholder.com/150X200/',2014);
INSERT INTO libro (nombre,sinopsis,portada,anio)  values('A Gentleman in Moscow: A Novel','esta es la sinopsis','https://via.placeholder.com/150X200/',2017);
INSERT INTO libro (nombre,sinopsis,portada,anio)  values('A Higher Loyalty: Truth, Lies, and Leadership','esta es la sinopsis','https://via.placeholder.com/150X200/',2018);
INSERT INTO libro (nombre,sinopsis,portada,anio)  values('A Man Called Ove: A Novel','esta es la sinopsis','https://via.placeholder.com/150X200/',2016);
INSERT INTO libro (nombre,sinopsis,portada,anio)  values('A Man Called Ove: A Novel','esta es la sinopsis','https://via.placeholder.com/150X200/',2017);
INSERT INTO libro (nombre,sinopsis,portada,anio)  values('A Stolen Life: A Memoir','esta es la sinopsis','https://via.placeholder.com/150X200/',2011);
INSERT INTO libro (nombre,sinopsis,portada,anio)  values('A Wrinkle in Time (Time Quintet)','esta es la sinopsis','https://via.placeholder.com/150X200/',2018);
INSERT INTO libro (nombre,sinopsis,portada,anio)  values('Act Like a Lady, Think Like a Man: What Men Really Think About Love, Relationships, Intimacy, and Commitment','esta es la sinopsis','https://via.placeholder.com/150X200/',2009);
INSERT INTO libro (nombre,sinopsis,portada,anio)  values('Adult Coloring Book Designs: Stress Relief Coloring Book: Garden Designs, Mandalas, Animals, and Paisley Patterns','esta es la sinopsis','https://via.placeholder.com/150X200/',2016);
INSERT INTO libro (nombre,sinopsis,portada,anio)  values('Adult Coloring Book: Stress Relieving Animal Designs','esta es la sinopsis','https://via.placeholder.com/150X200/',2015);
INSERT INTO libro (nombre,sinopsis,portada,anio)  values('Adult Coloring Book: Stress Relieving Patterns','esta es la sinopsis','https://via.placeholder.com/150X200/',2015);
INSERT INTO libro (nombre,sinopsis,portada,anio)  values('Adult Coloring Books: A Coloring Book for Adults Featuring Mandalas and Henna Inspired Flowers, Animals, and PaisleyÃ¢â‚¬Â¦','esta es la sinopsis','https://via.placeholder.com/150X200/',2015);
INSERT INTO libro (nombre,sinopsis,portada,anio)  values('Alexander Hamilton','esta es la sinopsis','https://via.placeholder.com/150X200/',2016);
INSERT INTO libro (nombre,sinopsis,portada,anio)  values('All the Light We Cannot See','esta es la sinopsis','https://via.placeholder.com/150X200/',2014);
INSERT INTO libro (nombre,sinopsis,portada,anio)  values('All the Light We Cannot See','esta es la sinopsis','https://via.placeholder.com/150X200/',2015);
INSERT INTO libro (nombre,sinopsis,portada,anio)  values('Allegiant','esta es la sinopsis','https://via.placeholder.com/150X200/',2013);
INSERT INTO libro (nombre,sinopsis,portada,anio)  values('American Sniper: The Autobiography of the Most Lethal Sniper in U.S. Military History','esta es la sinopsis','https://via.placeholder.com/150X200/',2015);
INSERT INTO libro (nombre,sinopsis,portada,anio)  values('And the Mountains Echoed','esta es la sinopsis','https://via.placeholder.com/150X200/',2013);
INSERT INTO libro (nombre,sinopsis,portada,anio)  values('Arguing with Idiots: How to Stop Small Minds and Big Government','esta es la sinopsis','https://via.placeholder.com/150X200/',2009);
INSERT INTO libro (nombre,sinopsis,portada,anio)  values('Astrophysics for People in a Hurry','esta es la sinopsis','https://via.placeholder.com/150X200/',2017);
INSERT INTO libro (nombre,sinopsis,portada,anio)  values('Autobiography of Mark Twain, Vol. 1','esta es la sinopsis','https://via.placeholder.com/150X200/',2010);
INSERT INTO libro (nombre,sinopsis,portada,anio)  values('Baby Touch and Feel: Animals','esta es la sinopsis','https://via.placeholder.com/150X200/',2015);
INSERT INTO libro (nombre,sinopsis,portada,anio)  values('Capital in the Twenty First Century','esta es la sinopsis','https://via.placeholder.com/150X200/',2014);
INSERT INTO libro (nombre,sinopsis,portada,anio)  values('Catching Fire (The Hunger Games)','esta es la sinopsis','https://via.placeholder.com/150X200/',2010);
INSERT INTO libro (nombre,sinopsis,portada,anio)  values('Catching Fire (The Hunger Games)','esta es la sinopsis','https://via.placeholder.com/150X200/',2011);
INSERT INTO libro (nombre,sinopsis,portada,anio)  values('Catching Fire (The Hunger Games)','esta es la sinopsis','https://via.placeholder.com/150X200/',2012);
INSERT INTO libro (nombre,sinopsis,portada,anio)  values('Cravings: Recipes for All the Food You Want to Eat: A Cookbook','esta es la sinopsis','https://via.placeholder.com/150X200/',2016);
INSERT INTO libro (nombre,sinopsis,portada,anio)  values('Crazy Love: Overwhelmed by a Relentless God','esta es la sinopsis','https://via.placeholder.com/150X200/',2009);
INSERT INTO libro (nombre,sinopsis,portada,anio)  values('Crazy Love: Overwhelmed by a Relentless God','esta es la sinopsis','https://via.placeholder.com/150X200/',2010);
INSERT INTO libro (nombre,sinopsis,portada,anio)  values('Crazy Love: Overwhelmed by a Relentless God','esta es la sinopsis','https://via.placeholder.com/150X200/',2011);
INSERT INTO libro (nombre,sinopsis,portada,anio)  values('Crazy Rich Asians (Crazy Rich Asians Trilogy)','esta es la sinopsis','https://via.placeholder.com/150X200/',2018);
INSERT INTO libro (nombre,sinopsis,portada,anio)  values('Creative Haven Creative Cats Coloring Book (Adult Coloring)','esta es la sinopsis','https://via.placeholder.com/150X200/',2015);
INSERT INTO libro (nombre,sinopsis,portada,anio)  values('Creative Haven Owls Coloring Book (Adult Coloring)','esta es la sinopsis','https://via.placeholder.com/150X200/',2015);
INSERT INTO libro (nombre,sinopsis,portada,anio)  values('Cutting for Stone','esta es la sinopsis','https://via.placeholder.com/150X200/',2010);
INSERT INTO libro (nombre,sinopsis,portada,anio)  values('Cutting for Stone','esta es la sinopsis','https://via.placeholder.com/150X200/',2011);
INSERT INTO libro (nombre,sinopsis,portada,anio)  values('Daring Greatly: How the Courage to Be Vulnerable Transforms the Way We Live, Love, Parent, and Lead','esta es la sinopsis','https://via.placeholder.com/150X200/',2013);
INSERT INTO libro (nombre,sinopsis,portada,anio)  values('David and Goliath: Underdogs, Misfits, and the Art of Battling Giants','esta es la sinopsis','https://via.placeholder.com/150X200/',2013);
INSERT INTO libro (nombre,sinopsis,portada,anio)  values('Dead And Gone: A Sookie Stackhouse Novel (Sookie Stackhouse/True Blood)','esta es la sinopsis','https://via.placeholder.com/150X200/',2009);
INSERT INTO libro (nombre,sinopsis,portada,anio)  values('Dead in the Family (Sookie Stackhouse/True Blood, Book 10)','esta es la sinopsis','https://via.placeholder.com/150X200/',2010);
INSERT INTO libro (nombre,sinopsis,portada,anio)  values('Dead Reckoning (Sookie Stackhouse/True Blood, Book 11)','esta es la sinopsis','https://via.placeholder.com/150X200/',2011);
INSERT INTO libro (nombre,sinopsis,portada,anio)  values('Dear Zoo: A Lift-the-Flap Book','esta es la sinopsis','https://via.placeholder.com/150X200/',2015);
INSERT INTO libro (nombre,sinopsis,portada,anio)  values('Dear Zoo: A Lift-the-Flap Book','esta es la sinopsis','https://via.placeholder.com/150X200/',2016);
INSERT INTO libro (nombre,sinopsis,portada,anio)  values('Dear Zoo: A Lift-the-Flap Book','esta es la sinopsis','https://via.placeholder.com/150X200/',2017);
INSERT INTO libro (nombre,sinopsis,portada,anio)  values('Dear Zoo: A Lift-the-Flap Book','esta es la sinopsis','https://via.placeholder.com/150X200/',2018);
INSERT INTO libro (nombre,sinopsis,portada,anio)  values('Decision Points','esta es la sinopsis','https://via.placeholder.com/150X200/',2010);
INSERT INTO libro (nombre,sinopsis,portada,anio)  values('Delivering Happiness: A Path to Profits, Passion, and Purpose','esta es la sinopsis','https://via.placeholder.com/150X200/',2010);
INSERT INTO libro (nombre,sinopsis,portada,anio)  values('Diagnostic and Statistical Manual of Mental Disorders, 5th Edition: DSM-5','esta es la sinopsis','https://via.placeholder.com/150X200/',2013);
INSERT INTO libro (nombre,sinopsis,portada,anio)  values('Diagnostic and Statistical Manual of Mental Disorders, 5th Edition: DSM-5','esta es la sinopsis','https://via.placeholder.com/150X200/',2014);
INSERT INTO libro (nombre,sinopsis,portada,anio)  values('Diary of a Wimpy Kid: Hard Luck, Book 8','esta es la sinopsis','https://via.placeholder.com/150X200/',2013);
INSERT INTO libro (nombre,sinopsis,portada,anio)  values('Diary of a Wimpy Kid: The Last Straw (Book 3)','esta es la sinopsis','https://via.placeholder.com/150X200/',2009);
INSERT INTO libro (nombre,sinopsis,portada,anio)  values('Diary of a Wimpy Kid: The Long Haul','esta es la sinopsis','https://via.placeholder.com/150X200/',2014);
INSERT INTO libro (nombre,sinopsis,portada,anio)  values('Difficult Riddles For Smart Kids: 300 Difficult Riddles And Brain Teasers Families Will Love (Books for Smart Kids)','esta es la sinopsis','https://via.placeholder.com/150X200/',2019);
INSERT INTO libro (nombre,sinopsis,portada,anio)  values('Divergent','esta es la sinopsis','https://via.placeholder.com/150X200/',2013);
INSERT INTO libro (nombre,sinopsis,portada,anio)  values('Divergent','esta es la sinopsis','https://via.placeholder.com/150X200/',2014);
INSERT INTO libro (nombre,sinopsis,portada,anio)  values('Divergent / Insurgent','esta es la sinopsis','https://via.placeholder.com/150X200/',2014);
INSERT INTO libro (nombre,sinopsis,portada,anio)  values('Divine Soul Mind Body Healing and Transmission System: The Divine Way to Heal You, Humanity, Mother Earth, and AllÃ¢â‚¬Â¦','esta es la sinopsis','https://via.placeholder.com/150X200/',2009);
INSERT INTO libro (nombre,sinopsis,portada,anio)  values('Doctor Sleep: A Novel','esta es la sinopsis','https://via.placeholder.com/150X200/',2013);
INSERT INTO libro (nombre,sinopsis,portada,anio)  values('Dog Days (Diary of a Wimpy Kid, Book 4) (Volume 4)','esta es la sinopsis','https://via.placeholder.com/150X200/',2009);
INSERT INTO libro (nombre,sinopsis,portada,anio)  values('Dog Man and Cat Kid: From the Creator of Captain Underpants (Dog Man #4)','esta es la sinopsis','https://via.placeholder.com/150X200/',2018);
INSERT INTO libro (nombre,sinopsis,portada,anio)  values('Dog Man: A Tale of Two Kitties: From the Creator of Captain Underpants (Dog Man #3)','esta es la sinopsis','https://via.placeholder.com/150X200/',2017);
INSERT INTO libro (nombre,sinopsis,portada,anio)  values('Dog Man: Brawl of the Wild: From the Creator of Captain Underpants (Dog Man #6)','esta es la sinopsis','https://via.placeholder.com/150X200/',2018);
INSERT INTO libro (nombre,sinopsis,portada,anio)  values('Dog Man: Brawl of the Wild: From the Creator of Captain Underpants (Dog Man #6)','esta es la sinopsis','https://via.placeholder.com/150X200/',2019);
INSERT INTO libro (nombre,sinopsis,portada,anio)  values('Dog Man: Fetch-22: From the Creator of Captain Underpants (Dog Man #8)','esta es la sinopsis','https://via.placeholder.com/150X200/',2019);
INSERT INTO libro (nombre,sinopsis,portada,anio)  values('Dog Man: For Whom the Ball Rolls: From the Creator of Captain Underpants (Dog Man #7)','esta es la sinopsis','https://via.placeholder.com/150X200/',2019);
INSERT INTO libro (nombre,sinopsis,portada,anio)  values('Dog Man: Lord of the Fleas: From the Creator of Captain Underpants (Dog Man #5)','esta es la sinopsis','https://via.placeholder.com/150X200/',2018);
INSERT INTO libro (nombre,sinopsis,portada,anio)  values('Double Down (Diary of a Wimpy Kid #11)','esta es la sinopsis','https://via.placeholder.com/150X200/',2016);
INSERT INTO libro (nombre,sinopsis,portada,anio)  values('Dover Creative Haven Art Nouveau Animal Designs Coloring Book (Creative Haven Coloring Books)','esta es la sinopsis','https://via.placeholder.com/150X200/',2015);
INSERT INTO libro (nombre,sinopsis,portada,anio)  values('Drive: The Surprising Truth About What Motivates Us','esta es la sinopsis','https://via.placeholder.com/150X200/',2010);
INSERT INTO libro (nombre,sinopsis,portada,anio)  values('Eat This Not That! Supermarket Survival Guide: The No-Diet Weight Loss Solution','esta es la sinopsis','https://via.placeholder.com/150X200/',2009);
INSERT INTO libro (nombre,sinopsis,portada,anio)  values('Eat This, Not That! Thousands of Simple Food Swaps that Can Save You 10, 20, 30 Pounds--or More!','esta es la sinopsis','https://via.placeholder.com/150X200/',2009);
INSERT INTO libro (nombre,sinopsis,portada,anio)  values('Eat to Live: The Amazing Nutrient-Rich Program for Fast and Sustained Weight Loss, Revised Edition','esta es la sinopsis','https://via.placeholder.com/150X200/',2011);
INSERT INTO libro (nombre,sinopsis,portada,anio)  values('Eat to Live: The Amazing Nutrient-Rich Program for Fast and Sustained Weight Loss, Revised Edition','esta es la sinopsis','https://via.placeholder.com/150X200/',2012);